#file: noinspection SpringBootApplicationYaml
#dev环境下的配置文件
gulimall:
  db:
    name: gulimall_pms
  product:
    thread:
      corePoolSize: 20
      maxPoolSize: 200
      keepAliveTime: 60s
spring:
  thymeleaf:
    cache: false