#springBoot核心配置文件
server:
  port: 88
spring:
  cloud:
    gateway:
      routes:
#        - id: gulimall-coupon
#          uri: lb://gulimall-coupon
        - id: gulimall-member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - StripPrefix=1
#        - id: gulimall-order
#          uri: lb://gulimall-order
        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1 #去掉一级路径
        - id: gulimall-ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - StripPrefix=1
        - id: gulimall-thirdParty
          uri: lb://gulimall-thirdParty
          predicates:
            - Path=/api/thirdParty/**
          filters:
            - StripPrefix=2
        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
        - id: gulimall-product-by-host
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com, item.gulimall.com
        - id: gulimall-search-by-host
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com